apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoicemgrtestscheduler
  labels:
    app: invoicemgrtestschedulerapp
spec:
  selector:
    matchLabels:
      app: invoicemgrtestschedulerapp
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicemgrtestschedulerapp
    spec:
      containers:
      - name: invoicemgrtestscheduler
        image: x00159358/invoicemgrtestscheduler:1.0.0-SNAPSHOT
        env:
         - name: ENDPOINT
           value: "http://broker-ingress.knative-eventing.svc.cluster.local/default/example-broker"
#           value: "https://invoicemgr.northeurope-1.eventgrid.azure.net/api/events?overload=cloudEvent&api-version=2018-01-01"
         - name: CID
           value: "uWKbOUKZ/qoFGnHFiEugJCAqzRcr8R+pWRo7szJibTE="
         - name: TPS
           value: "1"
